### PR TITLE
Fixed front end tests

### LINKED ISSUE #259: Restructure dependency injection
It's quite troublesome right now to inject our dependencies via the constructors

e.g.
```
constructor: function(options = {}) {
        this.app     = options.app     || global.App;
        this.Helpers = options.Helpers || require('utils/helpers');
        Marionette.ItemView.prototype.constructor.call(this, options);
},

// then later we have to call "this.Helpers.whatever"
```

There's some node libraries that help with dependency injections when writing tests such as https://www.npmjs.com/package/rewire

### PR DESCRIPTION
**Pull request by Trinovantes**
Misc:
- Renamed tests to camel case
- Replaced var with let
- Run tests with gulp instead of command line for more control

Changes:
- Use proxyquire for dependency injection for tests
- Moved SanaApp tests to new file
- Smoke test is literally a smoke test

Closes #259

### CODE REVIEW

**Comment by Ommy** [comment]
lgtm

File: src-backbone/gulpfile.js [hunk 1]
```diff
@@ -79,56 +79,57 @@ gulp.task('css', function() {
...
-    var filter = require('gulp-filter');
-
-    var js_filter = filter('**/*.js');
+    let jshint = require('gulp-jshint'); // Note: we're using JSHint, a better fork of the original JSLint
+    let stylish = require('jshint-stylish');
+    let filter = require('gulp-filter');
 
     gulp.src(Config.javascripts)
-        .pipe(js_filter)
+        .pipe(filter('**/*.js'))
```
Comment (Kapin) [inline src-backbone/gulpfile.js]: why did this change?

**Comment by Kapin** [comment]
Just one question otherwise lgtm

File: src-backbone/gulpfile.js (hunk 1 above)
Comment (Trinovantes) [inline src-backbone/gulpfile.js]: Wanted to clean up simple variables. In hindsight, this was a bad idea as I need to add this back because the filter needs more rules in another commit

Comment (Kapin) [inline src-backbone/gulpfile.js]: sounds good. lgtm after that
